### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by CodeAlDente** [aaronlauterer/contao-la-bookingcal#2]
First of all, thanks a lot for this extension!

It's very simple and works perfectly for me. But I'd like to know if there is any chance to not only book for a day but hourly or even per minute?

And, are there any plans for a special booking form where the date (and hopefully time) are stored automatically in the database so the owner has just to approve the request?

**Comment by aaronlauterer** [comment]
Thank you for your feedback!

Regarding your questions:
1. Having the option to book on an hourly and minute level would be possible in general. But that would require quite some change in the output logic.
2. There are no immediate plans to implement a full reservation / booking system right now.

I am currently running low on spare time that I could devote to this project. Should I have some free time I will think about your proposals. The first should be doable while the second one is quite a bit more work and not necessary for the website for which I created this extension in the beginning.

**Comment by CodeAlDente** [comment]
Thanks for your reply.

Have you some news for us? I'm having more and more situations the last days where I urgently need to set events per hour.

I understand that option 2 is more complicated than option 1. Maybe you can do this if you find some more time. I appreciate your valuable time.

**Comment by CodeAlDente** [comment]
I don't want to bother you, but do you have any news on that?

**Comment by aaronlauterer** [comment]
I am sorry but I don't have the time to work on the module

You can try to do the code modifications yourself. If I remember correctly you would have to adjust the regex and datepicker values for the two time fields in the dca/tl_la_bookingcal_dates.php to allow a finer time resolution and if needed change the eval functions at the bottom of that file should they make problems with the changes.

That would be for the back end. How you gonna visualize it in the front end template is up to you and your needs!
